version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    ports:
      - "5051:5432"
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    external: false
