// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASZ4YZTyF38kC94oXNt4EWDe9ViEWBJ-c',
    appId: '1:26861052783:web:ccc6ada378f3c517d17e9a',
    messagingSenderId: '26861052783',
    projectId: 'funight-383f9',
    authDomain: 'funight-383f9.firebaseapp.com',
    storageBucket: 'funight-383f9.firebasestorage.app',
    measurementId: 'G-NNGPL09Y83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZSjlQv4bZeATkENgGYpptsqWBwZXpu5Q',
    appId: '1:26861052783:android:74151227f40f5b80d17e9a',
    messagingSenderId: '26861052783',
    projectId: 'funight-383f9',
    storageBucket: 'funight-383f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn5QBcBuJR97a8fB12HyPrVRpbOCgJufQ',
    appId: '1:26861052783:ios:0c75c229507fd389d17e9a',
    messagingSenderId: '26861052783',
    projectId: 'funight-383f9',
    storageBucket: 'funight-383f9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn5QBcBuJR97a8fB12HyPrVRpbOCgJufQ',
    appId: '1:26861052783:ios:0c75c229507fd389d17e9a',
    messagingSenderId: '26861052783',
    projectId: 'funight-383f9',
    storageBucket: 'funight-383f9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASZ4YZTyF38kC94oXNt4EWDe9ViEWBJ-c',
    appId: '1:26861052783:web:6d463c65e94fd66dd17e9a',
    messagingSenderId: '26861052783',
    projectId: 'funight-383f9',
    authDomain: 'funight-383f9.firebaseapp.com',
    storageBucket: 'funight-383f9.firebasestorage.app',
    measurementId: 'G-KX4D3B894R',
  );
}
